### ISSUE TITLE
06-03_Primer_sample_DeskPlacement custom node ViewsToOutside is missing

### ISSUE THREAD

**Issue by KenLP** [DynamoDS/RefineryPrimer#11]
## Situation right now
Custom node ViewsToOutside is missing, cannot find in Dynamo Packages.

## What improvement do you suggest ?

Could you share this custom node?

## How would this change improve the Primer ?

Understand this example

## Are you ready to write the content for this change ?

- [ ] Yes
- [x] No

**Comment by SHKnudsen** [comment]
Hi @KenLP,

You can find the node you are looking for in the SpacePlanning package in the RefineryToolkits (https://github.com/DynamoDS/RefineryToolkits/releases).

Keep in mind that the package is still undergoing changes, but you should be able to take it for a test spin. 
The Package will soon be released to the package manager, so keep an eye out for the final release.

Please report any issues you may experience to the RefineryToolkits GitHub (https://github.com/DynamoDS/RefineryToolkits)

**Comment by KenLP** [comment]
Thank you so much for your support. It works with the SpacePlanning package.
