### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by amagio** [DynamoDS/RefineryPrimer#41]
## Situation right now

There is a spelling mistake in the "Defining Goals" section: https://refineryprimer.dynamobim.org/02-deeper-dive/02-03_optimization/02-03-05_defining-goals

## What improvement do you suggest ?

Spelling mistake is in this sentence:

Being able to confidently answer at least some of the above, is a good first step to **home** in on precisely what objectives your computational procedure should have.

**home** should be corrected to "**hone**"

## How would this change improve the Primer ?

Improves understanding.

## Are you ready to write the content for this change ?

- [x] Yes
- [ ] No

**Comment by amagio** [comment]
Being able to confidently answer at least some of the above, is a good first step to hone in on precisely what objectives your computational procedure should have.

**Comment by radumg** [comment]
Thanks @amagio for spotting this, fixed now ! Please also feel free to make a PR if you spot anything else and would like to fix it directly.

Thanks again.
