### ISSUE TITLE
[Proposed Changes] - Sample File Upgrade / Testing / Fix / Record Video?

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/RefineryPrimer#97]
Link:
https://www.generativedesign.org/04-sample-workflows/04-02_architectural-workflows/04-02-01_building-mass-generator

Tasks:
- [x]  Revise sample to Dynamo 2.13

Estimated Effort to Fix:
5/5

**Comment by johnpierson** [comment]
This one might be fine as-is, need to confirm with @lillismith

**Comment by lillismith** [comment]
Same story, don't need video, do need upgraded DYN that works in 2.13
